# Generated by Django 6.0.4 on 2026-04-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_material_product', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Material_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_material', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('price_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('qty_werehouse', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('min_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('qty_pack', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unit', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'Materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zak_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('avg_delivery', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Material_suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_material', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('percent_lost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Material_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arcticle', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('name_product', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_product', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('coeff_product', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Product_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('desc_perm', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_supplier', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('name_supplier', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('inn', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('full_name', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('email', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
                ('active', models.CharField(db_collation='Cyrillic_General_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
